
development:
  adapter: mysql2
  encoding: utf8
  database: MicroTutos_development
  pool: 5
  username: root
  password: bootcamp
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: MicroTutos_test
  pool: 5
  username: root
  password: bootcamp
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: MicroTutos_production
  pool: 5
  username: root
  password: bootcamp
  socket: /var/run/mysqld/mysqld.sock
